# Generated by Django 5.2.12 on 2026-04-06 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
        migrations.AddField(
            model_name='game',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
